### ISSUE TITLE
error

### ISSUE THREAD

**Issue by orarange** [NightfallGT/Discord-QR-Scam#12]
Does this work with non-smartphones?
Also, I get this in the terminal after loading on my smart phone.
What should I do?
```Traceback (most recent call last):
  File "C:\Users\sgiga\vscode\qr_generator.py", line 84, in <module>
    main()
  File "C:\Users\sgiga\vscode\qr_generator.py", line 60, in main
    token = driver.execute_script('''
  File "C:\Users\sgiga\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 872, in execute_script
    return self.execute(command, {
  File "C:\Users\sgiga\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "C:\Users\sgiga\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: webpackJsonp is not defined
  (Session info: chrome=96.0.4664.45)
Stacktrace:
Backtrace:
        Ordinal0 [0x00286903+2517251]
        Ordinal0 [0x0021F8E1+2095329]
        Ordinal0 [0x00122848+1058888]
        Ordinal0 [0x00124F44+1068868]
        Ordinal0 [0x00124E0E+1068558]
        Ordinal0 [0x001256BA+1070778]
        Ordinal0 [0x001764F9+1402105]
        Ordinal0 [0x001664D3+1336531]
        Ordinal0 [0x00175BBF+1399743]
        Ordinal0 [0x0016639B+1336219]
        Ordinal0 [0x001427A7+1189799]
        Ordinal0 [0x00143609+1193481]
        GetHandleVerifier [0x00415904+1577972]
        GetHandleVerifier [0x004C0B97+2279047]
        GetHandleVerifier [0x00316D09+534521]
        GetHandleVerifier [0x00315DB9+530601]
        Ordinal0 [0x00224FF9+2117625]
        Ordinal0 [0x002298A8+2136232]
        Ordinal0 [0x002299E2+2136546]
        Ordinal0 [0x00233541+2176321]
        BaseThreadInitThunk [0x76C1FA29+25]
        RtlGetAppContainerNamedObjectPath [0x77677A9E+286]
        RtlGetAppContainerNamedObjectPath [0x77677A6E+238]
        (No symbol) [0x00000000]
```

**Comment by medovi40k** [comment]
I don't really know the discord, but as I understand it, he changed the policy and removed access by push. I rewrite 
the code and now it works.
[click](https://github.com/medovi40k/Discord-QR-Scam)

**Comment by orarange** [comment]
@medovi40k 
thanks
