### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by lolo773** [NightfallGT/Discord-QR-Scam#25]
```
qr_generator.py:31: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
- Page loaded.
Traceback (most recent call last):
  File "qr_generator.py", line 85, in <module>
    main()
  File "qr_generator.py", line 42, in main
    qr_code = div.find('img')['src']
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by ghost** [comment]
I know why this is happening, its because in line 41:
 div = soup.find('div', {'class': 'qrCodeOverlay-2bLtKl'})
you have to put this instead of what you have: qrCodeOverlay-2bLtKl 
thats because discord has changed its class and that's why selenium has trouble finding the qr code...

**Comment by Cracken211** [comment]
Open "QR_Generator.py" and replace line 42 with the following:
qr_code = soup.find('img')['src']
