### ISSUE TITLE
Help Please, İts Not Working?

### ISSUE THREAD

**Issue by ZaddesXy** [NightfallGT/Discord-QR-Scam#31]
github.com/NightfallGT/Discord-QR-Scam

** QR Code Scam Generator **
C:\Users\akars\OneDrive\Masaüstü\Discord-QR-Scam-main\qr_generator.py:31: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
- Page loaded.
Traceback (most recent call last):
  File "C:\Users\akars\OneDrive\Masaüstü\Discord-QR-Scam-main\qr_generator.py", line 85, in <module>
    main()
  File "C:\Users\akars\OneDrive\Masaüstü\Discord-QR-Scam-main\qr_generator.py", line 42, in main
    qr_code = div.find('img')['src']
AttributeError: 'NoneType' object has no attribute 'find'

C:\Users\akars\OneDrive\Masaüstü\Discord-QR-Scam-main>pause
Press any key to continue . . .

**Comment by DOKKAEBIx** [comment]
sorry this is late but you may have to get a newer chromed driver

**Comment by jack-temko** [comment]
You could also try this one: https://github.com/ThatTSGuy/discord-qr-token-grabber
