### ISSUE TITLE
I keep geting error

### ISSUE THREAD

**Issue by Adadeane** [NightfallGT/Discord-QR-Scam#43]
** QR Code Scam Generator **
Traceback (most recent call last):
  File "qr_generator.py", line 85, in <module>
    main()
  File "qr_generator.py", line 31, in main
    driver = webdriver.Chrome(options=options, executable_path=r'chromedriver.exe')
TypeError: __init__() got an unexpected keyword argument 'executable_path'

**Comment by Pioniergier** [comment]
me to

**Comment by hirusha-adi** [comment]
The original repository seems to be unmaintained. I've got a working fork of this: https://github.com/hirusha-adi/Discord-Token-Grabber-by-QR

Maybe check it out.

**Comment by Wave3prime15** [comment]
> The original repository seems to be unmaintained. I've got a working fork of this: https://github.com/hirusha-adi/Discord-Token-Grabber-by-QR
> 
> Maybe check it out.

that doesent even work too cro
